import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import StoreProvider from "@/app/StoreProvider";
import { Provider } from "react-redux";
import {store} from "@/lib/store";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Bookstore",
  description: "Generated by ugur hikmet kose",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
      <StoreProvider >
        <Header />
        {children}
        </StoreProvider>
      </body>
    </html>

  );
}
